// generates src/shared/Items/ItemData.luau from rolimons (rap/value) and the roblox catalog (asset type, year).
// usage: node tools/generate-items.mjs
// rerun whenever you want fresh values. the output file is overwritten, never edit it by hand.

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "shared", "Items", "ItemData.luau");
const ROLIMONS = "https://api.rolimons.com/items/v2/itemdetails";
const CATALOG = "https://catalog.roblox.com/v1/catalog/items/details";
const BATCH = 120;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchRolimons() {
	const res = await fetch(ROLIMONS);
	if (!res.ok) throw new Error(`rolimons ${res.status}`);
	const json = await res.json();
	if (!json.success) throw new Error("rolimons returned success=false");
	return json.items;
}

let csrf = "";
async function fetchCatalogBatch(ids, attempt = 0) {
	const body = JSON.stringify({ items: ids.map((id) => ({ itemType: "Asset", id: Number(id) })) });
	const res = await fetch(CATALOG, {
		method: "POST",
		headers: { "content-type": "application/json", "x-csrf-token": csrf },
		body,
	});
	if (res.status === 403 && res.headers.get("x-csrf-token")) {
		csrf = res.headers.get("x-csrf-token");
		return fetchCatalogBatch(ids, attempt);
	}
	if (res.status === 429 && attempt < 10) {
		await sleep(5000 * (attempt + 1));
		return fetchCatalogBatch(ids, attempt + 1);
	}
	if (!res.ok) throw new Error(`catalog ${res.status}`);
	return (await res.json()).data;
}

function luaString(s) {
	return JSON.stringify(s ?? "").replace(/\\u([0-9a-fA-F]{4})/g, "\\u{$1}");
}

async function main() {
	console.log("fetching rolimons...");
	const items = await fetchRolimons();
	const ids = Object.keys(items);
	console.log(`${ids.length} limiteds`);

	const meta = {};
	for (let i = 0; i < ids.length; i += BATCH) {
		const chunk = ids.slice(i, i + BATCH);
		const data = await fetchCatalogBatch(chunk);
		for (const d of data) {
			meta[d.id] = { assetType: d.assetType, year: d.itemCreatedUtc ? new Date(d.itemCreatedUtc).getUTCFullYear() : 0 };
		}
		process.stdout.write(`\rcatalog ${Math.min(i + BATCH, ids.length)}/${ids.length}`);
		await sleep(1500);
	}
	console.log();

	const lines = [];
	let skipped = 0;
	for (const id of ids.sort((a, b) => Number(a) - Number(b))) {
		const [name, acronym, rap, value] = items[id];
		const m = meta[id];
		if (!m || rap <= 0) {
			skipped++;
			continue;
		}
		lines.push(
			`\t[${id}] = { name = ${luaString(name)}, acronym = ${luaString(acronym)}, rap = ${rap}, value = ${value > 0 ? value : rap}, valued = ${value > 0}, assetType = ${m.assetType}, year = ${m.year} },`,
		);
	}

	const header = [
		"-- generated by tools/generate-items.mjs, do not edit by hand. rerun the script to refresh values.",
		`-- generated ${new Date().toISOString().slice(0, 10)}, ${lines.length} items`,
		"",
		"return {",
	];
	await mkdir(dirname(OUT), { recursive: true });
	await writeFile(OUT, [...header, ...lines, "}", ""].join("\n"));
	console.log(`wrote ${lines.length} items (${skipped} skipped) to ${OUT}`);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
